name: Deploy to Server

on:
  workflow_run:
    workflows: ["ci"]   
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host:   ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key:  ${{ secrets.SSH_KEY }}
          port: 2298
          script_stop: true
          script: |
            cd /home/log1.health-ease-hospital.com
            if [ -d .git ]; then
              git pull origin main
            else
              git clone https://github.com/xdlemar/capstone-node.git .
            fi

          
            npm ci

            
            DATABASE_URL="${{ secrets.INVENTORY_DB_URL }}" \
            npx prisma migrate deploy --schema=inventory-svc/prisma/schema.prisma

            DATABASE_URL="${{ secrets.PROCUREMENT_DB_URL }}" \
            npx prisma migrate deploy --schema=procurement-svc/prisma/schema.prisma

            DATABASE_URL="${{ secrets.AUTH_DB_URL }}" \
            npx prisma migrate deploy --schema=auth-svc/prisma/schema.prisma

          

            if command -v pm2 >/dev/null 2>&1; then
              pm2 startOrReload ecosystem.config.js --update-env || true
              pm2 save || true
            fi
